#papermill RunModels_bck_densenet_t1t2_out_site16_norm.ipynb RunModels_bck_densenet_t1t2_out_site16_norm_out.ipynb
#papermill RunModels_bck_densenet_t1t2_out_site16_.ipynb RunModels_bck_densenet_t1t2_out_site16_out.ipynb
papermill RunModels_bck_densenet_t1t2_out_site16_onlyIntel.ipynb RunModels_bck_densenet_t1t2_out_site16_onlyIntel_out.ipynb
papermill RunModels_bck_densenet_t1t2_out_site16_SimpleCNN_.ipynb RunModels_bck_densenet_t1t2_out_site16_SimpleCNN_out.ipynb
papermill RunModels_bck_densenet_t1t2_out_site16_onlyIntel_SimpleCNN.ipynb RunModels_bck_densenet_t1t2_out_site16_onlyIntel_SimpleCNN_out.ipynb
papermill RunModels_bck_densenet_t1t2_out_site16_norm_simpleCNN.ipynb RunModels_bck_densenet_t1t2_out_site16_norm_simpleCNN_out.ipynb