papermill RunModels_run_down64_DenseNet_t1t2def.ipynb xx_t1t2def.ipynb
papermill RunModels_run_down64_medSimpleCNN_autofocus.ipynb xx_autofocus.ipynb
papermill RunModels_run_down64_DenseNet_def.ipynb xx_def.ipynb
papermill RunModels_run_down64_DenseNet_t1.ipynb xx_t1.ipynb
papermill RunModels_run_down64_DenseNet_t2.ipynb xx_t2.ipynb
papermill RunModels_run_cropped128.ipynb xx_out3.ipynb
papermill RunModels_run_down256.ipynb xx_out4.ipynb
