papermill RunModels_bck_densenet_t1t2_out_site16_norm.ipynb RunModels_bck_densenet_t1t2_out_site16_norm_out.ipynb
papermill RunModels_bck_densenet_t1t2_out_site16_.ipynb RunModels_bck_densenet_t1t2_out_site16_out.ipynb
papermill RunModels_bck_densenet_t1t2_out_onlyIntel.ipynb RunModels_bck_densenet_t1t2_out_onlyIntel_out.ipynb