papermill RunModels_bck_simplecnn_t1t2.ipynb RunModels_bck_simplecnn_t1t2_out.ipynb
papermill RunModels_bck_densenet_t1t2.ipynb RunModels_bck_densenet_t1t2_out.ipynb
papermill RunModels_bck_simplecnn_t1.ipynb RunModels_bck_simplecnn_t1_out.ipynb
papermill RunModels_bck_simplecnn_t2.ipynb RunModels_bck_simplecnn_t2_out.ipynb
papermill RunModels_bck_simplecnn_def.ipynb RunModels_bck_simplecnn_def_out.ipynb
papermill RunModels_bck_simplecnn_t1t2def.ipynb RunModels_bck_simplecnn_t1t2def_out.ipynb
papermill RunModels_bck_densenet_t1t2def.ipynb RunModels_bck_densenet_t1t2def_out.ipynb
